spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-69384545.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oa8baj6ltw6Tnl1h5d7
            client-secret: Oskp002yFVzvlFehc1j6DzaL7sd-sR58pJbhe77P

        provider:
          okta:
            issuer-uri: https://dev-69384545.okta.com/oauth2/default

okta:
  oauth2:
    issuer: https://dev-69384545.okta.com/oauth2/default
    audience: api://default
